name: PHP Lint

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.1
    - name: PHP Lint
      run: |
        pwd
#        git submodule update --init --recursive
        bash './php-lint.sh'
